const mongoose = require("mongoose");

const orderItemSchema = new mongoose.Schema(
  {
    productId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Product",
      required: true,
    },
    productName: { type: String, required: true, trim: true },
    category: { type: String, default: "", trim: true },
    image: { type: String, default: "" },
    quantityKg: { type: Number, required: true, min: 0.001 },
    pricePerKg: { type: Number, required: true, min: 0 },
    mrpPerKg: { type: Number, required: true, min: 0 },
    discountPercentage: { type: Number, required: true, min: 0, max: 100 },
    discountAmount: { type: Number, required: true, min: 0 },
    couponDiscount: { type: Number, default: 0, min: 0 },
    gstPercentage: { type: Number, required: true, min: 0, max: 100 },
    gstAmount: { type: Number, required: true, min: 0 },
    taxableAmount: { type: Number, required: true, min: 0 },
    itemTotal: { type: Number, required: true, min: 0 },
  },
  { _id: false },
);

const orderSchema = new mongoose.Schema(
  {
    orderNumber: { type: String, required: true, unique: true, index: true },
    clientRequestId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    items: {
      type: [orderItemSchema],
      required: true,
      validate: (items) => items.length > 0,
    },
    shippingAddress: {
      name: { type: String, required: true, trim: true },
      mobile: { type: String, required: true, match: /^[6-9]\d{9}$/ },
      address: { type: String, required: true, trim: true },
      fullAddress: { type: String, default: "", trim: true },
      building: { type: String, default: "", trim: true },
      houseNumber: { type: String, default: "", trim: true },
      road: { type: String, default: "", trim: true },
      locality: { type: String, default: "", trim: true },
      district: { type: String, default: "", trim: true },
      area: { type: String, default: "", trim: true },
      city: { type: String, default: "", trim: true },
      state: { type: String, default: "", trim: true },
      pincode: {
        type: String,
        default: "",
        validate: (value) => !value || /^\d{6}$/.test(value),
      },
      country: { type: String, default: "", trim: true },
      locationDetected: { type: Boolean, default: false },
      locationSource: {
        type: String,
        enum: ["gps", "manual"],
        default: "manual",
      },
      latitude: { type: Number, min: -90, max: 90 },
      longitude: { type: Number, min: -180, max: 180 },
    },
    shipping: {
      distanceKm: { type: Number, required: true, min: 0 },
      shippingCharge: { type: Number, required: true, min: 0 },
      distanceMethod: { type: String, enum: ["road", "haversine"] },
      geocodingPrecision: {
        type: String,
        enum: ["gps", "address", "postcode"],
      },
      destination: {
        latitude: { type: Number, required: true, min: -90, max: 90 },
        longitude: { type: Number, required: true, min: -180, max: 180 },
      },
      location: {
        fullAddress: { type: String, default: "" },
        building: { type: String, default: "" },
        houseNumber: { type: String, default: "" },
        road: { type: String, default: "" },
        locality: { type: String, default: "" },
        area: { type: String, default: "" },
        district: { type: String, default: "" },
        city: { type: String, default: "" },
        state: { type: String, default: "" },
        pincode: { type: String, default: "" },
        country: { type: String, default: "" },
      },
    },
    coupon: {
      couponId: { type: mongoose.Schema.Types.ObjectId, ref: "Coupon" },
      code: { type: String, default: "" },
      type: { type: String, default: "" },
      discount: { type: Number, default: 0, min: 0 },
      shippingDiscount: { type: Number, default: 0, min: 0 },
      originalShipping: { type: Number, default: 0, min: 0 },
      finalShipping: { type: Number, default: 0, min: 0 },
      campaignName: { type: String, default: "" },
    },
    pricing: {
      subtotal: { type: Number, required: true, min: 0 },
      discount: { type: Number, required: true, min: 0 },
      taxableAmount: { type: Number, required: true, min: 0 },
      totalGST: { type: Number, required: true, min: 0 },
      shippingCharges: { type: Number, required: true, min: 0 },
      couponDiscount: { type: Number, default: 0, min: 0 },
      shippingDiscount: { type: Number, default: 0, min: 0 },
      grandTotal: { type: Number, required: true, min: 0 },
    },
    paymentStatus: {
      type: String,
      enum: ["pending", "paid", "failed", "refunded", "cod"],
      default: "pending",
    },
    paymentMethod: {
      type: String,
      enum: ["cod", "online", "razorpay"],
      default: "cod",
    },
    paymentId: { type: String, default: "" },
    razorpayOrderId: { type: String, default: "" },
    razorpayPaymentId: { type: String, default: "" },
    razorpaySignature: { type: String, default: "" },
    orderStatus: {
      type: String,
      enum: ["received", "confirmed", "shipped", "delivered", "cancelled"],
      default: "received",
      index: true,
    },
    cancellationReason: {
      type: String,
      default: "",
      trim: true,
      maxlength: 500,
    },
    cancelledBy: { type: String, enum: ["user", "admin", ""], default: "" },
    cancelledAt: { type: Date, default: null },
  },
  { timestamps: true },
);

module.exports = mongoose.model("Order", orderSchema);
